name: CI
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

# jobs запускаются параллельно, если не указана последовательность
jobs:
    # Название job вы можете назвать как угодно
    my_build_job:
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: ubuntu-latest
        # Шаги
      steps:
          # Actions от github: проверяет репозиторий, гит и т.д.
          - uses: actions/checkout@v3

          - name: Run a one-line script
            run: python3 unittesting/rectangle_test.py
